networks:
    ledger:
        driver: bridge

services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8001:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/app:delegated
        depends_on:
            - app
        networks:
            - ledger
    app:
        build: .
        restart: unless-stopped
        tty: true
        expose:
            - "9000"
        volumes:
            - .:/var/www/app:delegated
        command: composer install && php-fpm
        networks:
            - ledger
    crdb:
        image: cockroachdb/cockroach:v19.2.2
        ports:
            - "26257:26257"
            - "8080:8080"
        command: start-single-node --insecure
        volumes:
            - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
        networks:
            - ledger
